#!/usr/bin/env php
<?php
/**
 * Automated project setup
 */

// If .env file already exists, exit immediately
if (file_exists('.env')) {
    fwrite(\STDOUT, 'Aborting setup, the .env file already exists!'.PHP_EOL);
    exit();
}

// ================================================================================ //

// Collect user information
$config = [
    'username' => getenv('SETUP_USERNAME'),
    'password' => getenv('SETUP_PASSWORD'),
    'database' => getDbName(),
    // 'database' => prompt('Database: ', getDbName()),

    'siteUrl'  => 'http://'.basename(__DIR__).'.test',
    'sitePath' => __DIR__.'/public',
];

setupDatabase($config);
setupEnvFile($config);
setupNpm();

// Output a link to the control panel
fwrite(\STDOUT, PHP_EOL.'Hooray!! Your new site has been created...'.PHP_EOL);
fwrite(\STDOUT, $config['siteUrl'].'/cp'.PHP_EOL.PHP_EOL);

// All done!
exit();

// ================================================================================ //

function setupDatabase($config)
{
    // Get current database dump
    $files = glob(__DIR__.'/db/*');
    $sql = ($files ? $files[0] : false);

    // Connect to MySQL
    $mysql = new mysqli('127.0.0.1', $config['username'], $config['password']);

    // If can't connect to MySQL, fail
    if (!$mysql) {
        $error = mysqli_connect_error();
        echo "Unable to connect to MySQL: {$error}".PHP_EOL;
        exit();
    }

    // Create a new database
    echo "Creating a new database... ";
    $createdDatabase = (true === $mysql->query("CREATE DATABASE {$config['database']}"));

    // If couldn't create the database, fail
    if (!$createdDatabase) {
        echo PHP_EOL.$mysql->error.PHP_EOL;
        exit();
    }

    // Report database creation
    echo "Done. ({$config['database']})".PHP_EOL;

    // Import the SQL file
    echo "Importing SQL file... ";
    system("mysql --user={$config['username']} --password={$config['password']} {$config['database']} < {$sql}");
    $filename = basename($sql);
    echo "Done. (/db/{$filename})".PHP_EOL;

    // Close MySQL connection
    $mysql->close();
}

function setupEnvFile($config)
{
    // Copy example .env file
    copy('.env.example', '.env');

    // Get all existing settings from the .env file
    $settings = file_get_contents('.env');

    // Get replacement strings
    $replacements = getEnvReplacements($config);

    // Update all relevant settings
    foreach ($replacements as $key => $val) {
        $settings = str_replace($key, $val, $settings);
    }

    // Save new settings back to the .env file
    file_put_contents('.env', $settings);

    // Generate new security key
    system('./craft setup/security-key');
}

// Prep NPM and run initial front-end build
function setupNpm()
{
    system('npm install');
    system('npm audit fix');
    system('npm run dev');
}

// ================================================================================ //

// Determine database name based on current system and path info
function getDbName()
{
    // If not Lindsey's machine, just return current folder name
    if ('LD' !== getenv('SETUP_PATTERN')) {
        basename(__DIR__);
    }

    // Get Lindsey's current path info
    $path = str_replace('/Users/lindseydiloreto/Sites/', '', __DIR__);
    $dir = explode('/', $path);

    // Determine first part of database name
    switch ($dir[0]) {
        case 'etc':
        case 'workflow':
        case 'doublesecretagency':
            $primary = '2x';
            break;
        default:
            $primary = $dir[0];
            break;
    }

    // Determine second part of database name
    $secondary = array_pop($dir);

    // Return specially formatted database name
    return "{$primary}_{$secondary}";
}

function getEnvReplacements($config)
{
    // Strings to be updated in .env file
    $replacements = [
        // Enable test email address, point test emails to Lindsey
        '#CONFIG_TESTTOEMAILADDRESS="support@doublesecretagency.com"' =>
        'CONFIG_TESTTOEMAILADDRESS="lindsey@doublesecretagency.com"',
    ];

    // Updated settings for .env file
    $updatedValues = [
        'DB_USER'         => $config['username'],
        'DB_PASSWORD'     => $config['password'],
        'DB_DATABASE'     => $config['database'],
        'CONFIG_SITEURL'  => $config['siteUrl'],
        'CONFIG_SITEPATH' => $config['sitePath'],
    ];

    // Append all updated values
    foreach ($updatedValues as $key => $val) {
        $replacements["{$key}=\"\""] = "{$key}=\"{$val}\"";
    }

    // Return strings to be updated
    return $replacements;
}

// ================================================================================ //

//// Prompt user for new information
//function prompt($message, $default = false)
//{
//    // Include default value in message (if it exists)
//    if ($default) {
//        $message = rtrim($message, ': ');
//        $message = "{$message} [{$default}]: ";
//    }
//
//    // Display message prompt
//    fwrite(\STDOUT, $message);
//
//    // Get user response
//    $response = rtrim(fgets(\STDIN), PHP_EOL);
//
//    // If user responded, return their answer
//    if ($response) {
//        return $response;
//    }
//
//    // Return the default value
//    return $default;
//}
