#!/usr/bin/env php
<?php
/**
 * Keeps environments in sync after deployments
 */

// If there is no .env file, exit immediately
if (!file_exists('.env')) {
    fwrite(\STDOUT, 'Unable to sync, the .env file could not be found.'.PHP_EOL);
    exit();
}

// ================================================================================ //

system('./craft migrate/all');
system('./craft clear-caches/all');
